import { templateManifest } from '../templates/templateManifest'; // File generated by build process
import { renderKeymenu } from 'keymenu/orchestrator/keymenuOrchestrator';

/**
 * Loads partial HTML templates asynchronously and inserts them into the DOM.
 * Uses generated manifest for dynamic loading.
 * Should be called before initializing dependencies such as  global event
 * listeners and state subscriptions.
 * Called once on DOMContentLoaded.
 * @returns A promise that resolves when all templates are loaded and inserted.
 */
export async function loadPartialTemplates(): Promise<void> {
    await Promise.all(
        templateManifest.map(async ({ path, containerId }) => {
            try {
                const response = await fetch(path);
                if (!response.ok) {
                    console.error(`Failed to load template: ${path} (Status: ${response.status})`);
                    return;
                }
                const html = await response.text();
                const container = document.getElementById(containerId);
                if (container) {
                    container.innerHTML = html;
                } else {
                    console.warn(`Container not found for template: ${path} (id: ${containerId})`);
                }
            } catch (error) {
                console.error(`Error fetching template: ${path}`, error);
            }
        }),
    );

    // Render keymenu with dynamic data from API after templates are loaded
    await renderKeymenu();
}
